Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function New-StrongPassword {
  param([int]$Length = 24)

  $upper = 'ABCDEFGHJKLMNPQRSTUVWXYZ'.ToCharArray()
  $lower = 'abcdefghijkmnopqrstuvwxyz'.ToCharArray()
  $digit = '23456789'.ToCharArray()
  $symbol = '!@#$%^*()-_=+[]{}:,.?'.ToCharArray()

  $all = @($upper + $lower + $digit + $symbol)
  $chars = @(
    ($upper | Get-Random),
    ($lower | Get-Random),
    ($digit | Get-Random),
    ($symbol | Get-Random)
  )

  for ($i = $chars.Count; $i -lt $Length; $i++) {
    $chars += ($all | Get-Random)
  }

  -join ($chars | Sort-Object { Get-Random })
}

function Get-AzdEnvMap {
  $envMap = @{}
  $lines = azd env get-values 2>$null
  foreach ($line in $lines) {
    if ($line -match '^([^=]+)="?(.*)"?$') {
      $envMap[$matches[1]] = $matches[2].Trim('"')
    }
  }
  return $envMap
}

$envMap = Get-AzdEnvMap
$mode = if ($envMap.ContainsKey('DR_DEPLOYMENT_MODE')) { $envMap['DR_DEPLOYMENT_MODE'] } else { 'all' }

if ($mode -notin @('iaas', 'paas', 'all')) {
  throw "DR_DEPLOYMENT_MODE must be one of iaas, paas, all. Current value: $mode"
}

if (($mode -eq 'iaas' -or $mode -eq 'all') -and (-not $envMap.ContainsKey('DR_VM_ADMIN_PASSWORD') -or [string]::IsNullOrWhiteSpace($envMap['DR_VM_ADMIN_PASSWORD']))) {
  $generatedPassword = New-StrongPassword
  azd env set DR_VM_ADMIN_PASSWORD $generatedPassword | Out-Null
  azd env set DR_VM_ADMIN_PASSWORD_AUTOGENERATED true | Out-Null

  # Ensure the current process has the value for this azd run.
  $env:DR_VM_ADMIN_PASSWORD = $generatedPassword
  $envMap['DR_VM_ADMIN_PASSWORD'] = $generatedPassword

  Write-Host 'DR_VM_ADMIN_PASSWORD was empty. Generated a strong password automatically and saved it to azd env.'
}

# Auto-detect Entra ID admin for SQL if not already set
if ($mode -eq 'paas' -or $mode -eq 'all') {
  if (-not $envMap.ContainsKey('DR_SQL_AAD_ADMIN_OID') -or [string]::IsNullOrWhiteSpace($envMap['DR_SQL_AAD_ADMIN_OID'])) {
    Write-Host 'DR_SQL_AAD_ADMIN_OID not set — detecting from signed-in user...'
    $userJson = az ad signed-in-user show -o json 2>$null | ConvertFrom-Json
    if ($userJson) {
      azd env set DR_SQL_AAD_ADMIN_NAME $userJson.userPrincipalName
      azd env set DR_SQL_AAD_ADMIN_OID $userJson.id
      $tenantId = az account show --query tenantId -o tsv
      azd env set DR_SQL_AAD_ADMIN_TENANT $tenantId
      Write-Host "Set SQL Entra admin to $($userJson.userPrincipalName) ($($userJson.id))"
    } else {
      throw 'Cannot detect signed-in user for SQL Entra admin. Set DR_SQL_AAD_ADMIN_OID manually.'
    }
  }
}

$primary = if ($envMap.ContainsKey('AZURE_LOCATION')) { $envMap['AZURE_LOCATION'] } else { 'eastus2' }
$secondary = if ($envMap.ContainsKey('DR_SECONDARY_LOCATION')) { $envMap['DR_SECONDARY_LOCATION'] } else { 'westus2' }
if ($primary -eq $secondary) {
  throw 'AZURE_LOCATION and DR_SECONDARY_LOCATION must be different regions.'
}

az extension add --name site-recovery --upgrade --only-show-errors | Out-Null
Write-Host "Preprovision checks completed. mode=$mode primary=$primary secondary=$secondary"
